### PR TITLE
Make the build system CI/CD-friendly

### PR DESCRIPTION
**Pull request by ailispaw**
- Remove Vagrant dependency
- Don’t use non-interoperable commands (`stat` and `date`)  
  Please maintain .dockerignore file accordingly instead.

Cf.) https://github.com/bargees/barge-os/issues/81

ping @prologic

### CODE REVIEW

**Comment by prologic** [comment]
So... Can I just run `make` now with a `docker-machine` pre-configured daemon already running and activated with `eval $(docker-machine eval ...)`? :)

**Comment by ailispaw** [comment]
@prologic As long as you can execute `docker` command on your local terminal to the daemon, I can say yes.

**Comment by prologic** [comment]
Seems to be working with just:

```
$ git pull
$ git co ci
$ make
```

I'll post here with details on success or failure.

**Comment by ailispaw** [comment]
Thank you. :)

**Comment by prologic** [comment]
Something didn't quite work here:

```
mkdir -p -- ./libcc1
Configuring in ./libcc1
../../gcc/genhooks.c: In function 'void emit_documentation(const char*)':
../../gcc/genhooks.c:139:31: warning: ignoring return value of 'int fscanf(FILE*, const char*, ...)', declared with attribute warn_unused_result [-Wunused-result]
       fscanf (f, "%999s", buf);
                               ^
../../gcc/genhooks.c:130:3: warning: ignoring return value of 'int fscanf(FILE*, const char*, ...)', declared with attribute warn_unused_result [-Wunused-result]
   while (fscanf (f, "%*[^@]"), buf[0] = '\0',
   ^
../../gcc/genhooks.c:192:34: warning: ignoring return value of 'int fscanf(FILE*, const char*, ...)', declared with attribute warn_unused_result [-Wunused-result]
       fscanf (f, "%5[^ \n]", buf);
                                  ^
../../gcc/genhooks.c:198:31: warning: ignoring return value of 'int fscanf(FILE*, const char*, ...)', declared with attribute warn_unused_result [-Wunused-result]
       fscanf (f, "%999s", buf);
                               ^
gengtype-lex.c: In function 'int yy_get_next_buffer()':
gengtype-lex.c:2151:18: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
gengtype-lex.c:1343:20: note: in definition of macro 'YY_INPUT'
gengtype-lex.c: In function 'yy_buffer_state* yy_scan_bytes(const char*, yy_size_t)':
gengtype-lex.c:2658:19: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
GIMPLE decision tree has 1422 leafs, maximum depth 10 and a total number of 5470 nodes
removed 728 duplicate tails
GENERIC decision tree has 1422 leafs, maximum depth 10 and a total number of 5470 nodes
removed 728 duplicate tails
make[3]: *** [s-attrtab] Killed
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [all-gcc] Error 2
make[1]: *** [all] Error 2
make: *** [/build/buildroot/output/build/host-gcc-final-6.4.0/.stamp_built] Error 2
make: *** [build] Error 2
```

**Comment by ailispaw** [comment]
I don't see actual errors in your log, instead of "Error 2" and warnings.
Do you see error messages in it?

**Comment by ailispaw** [comment]
Actually I made it with this method successfully before I opened this pull request.

Could you provide your Docker environment for me?
Like Docker version, Linux version in your local machine and where the docker daemon is running, memory and disk space.

**Comment by prologic** [comment]
Nope that was the last relevant output I saw :/ I'll do some more digging...

**Comment by prologic** [comment]
I *think* it's this:

```
make[2]: *** [s-attrtab] Killed
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [all-gcc] Error 2
```

This *looks* like the damn VM (`docker-machine` installed) has run out of memory? I can destroy it and re-create with 2x the memory to rule this out. (*smells like an OOM to me*)

**Comment by prologic** [comment]
Sure:

```
prologic@Jamess-MacBook
Mon Jun 25 22:46:03
~/tmp/barge-os
 (ci) 2
$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

prologic@Jamess-MacBook
Mon Jun 25 23:12:27
~/tmp/barge-os
 (ci) 0
$ docker version
Client:
 Version:      18.05.0-ce
 API version:  1.30 (downgraded from 1.37)
 Go version:   go1.10.2
 Git commit:   f150324
 Built:        unknown-buildtime
 OS/Arch:      darwin/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      17.06.0-ce
  API version:  1.30 (minimum version 1.12)
  Go version:   go1.8.3
  Git commit:   02c1d87
  Built:        Fri Jun 23 21:51:55 2017
  OS/Arch:      linux/amd64
  Experimental: false

prologic@Jamess-MacBook
Mon Jun 25 23:12:30
~/tmp/barge-os
 (ci) 0
$ dm ssh default df -h
Filesystem                Size      Used Available Use% Mounted on
tmpfs                   896.2M    640.8M    255.4M  72% /
tmpfs                   497.9M         0    497.9M   0% /dev/shm
/dev/sda1                17.9G      4.7G     12.2G  28% /mnt/sda1
cgroup                  497.9M         0    497.9M   0% /sys/fs/cgroup
Users                   233.5G    126.4G    107.1G  54% /Users
/dev/sda1                17.9G      4.7G     12.2G  28% /mnt/sda1/var/lib/docker/aufs

prologic@Jamess-MacBook
Mon Jun 25 23:12:47
~/tmp/barge-os
 (ci) 0
$ dm ssh default free -m
             total       used       free     shared    buffers     cached
Mem:           995        261        734         17          2         32
-/+ buffers/cache:        227        768
Swap:         1142        642        500

prologic@Jamess-MacBook
Mon Jun 25 23:12:54
~/tmp/barge-os
 (ci) 0
$ dm ssh default uname -r
4.4.74-boot2docker
```

**Comment by ailispaw** [comment]
It might be OOM, I guess, too. I use it with 2G.

**Comment by prologic** [comment]
Looks like I'm using the default of 1GB RAM. I'll bump to 2GB and try again :)

**Comment by ailispaw** [comment]
Thank you for the information. It looks good, except memory.

**Comment by ailispaw** [comment]
Btw, why do you build it by yourself, instead of the released one I built?
Do you need the latest docker in Barge by default?

**Comment by prologic** [comment]
> Btw, why do you build it by yourself, instead of the released one I built?
> Do you need the latest docker in Barge by default?

Because I'm *looking* for something I can build on top of or contribute to ;) I'm the author of https://github.com/vallinux/ -- Big fan of Docker and Rancher OS; but lately Rancher OS is going down a path I don't like (*heavy resource requirements at boot time and idle*)

**Comment by ailispaw** [comment]
Thank you for sharing that.
I have realized the recent Rancher OS things, because I have checked it whenever they released. ;)
https://gist.github.com/ailispaw/da3ea53c1f42569770e0

**Comment by ailispaw** [comment]
And I have noted that boot2docker has a potential issue for the future, too.
https://github.com/boot2docker/boot2docker/pull/1322

You may need to switch from docker-machine to docker for mac or Barge for local dev.

**Comment by ailispaw** [comment]
Val Linux is interesting. I will check it out. :)

**Comment by prologic** [comment]
> Thank you for sharing that.
> I have realized the recent Rancher OS things, because I have checked it whenever they released. ;)
> https://gist.github.com/ailispaw/da3ea53c1f42569770e0

😱I love this! Nice work! I've been using Docker since 0.7.x and Rancher OS since pre v1.0 I use it for my home infra and some small clusters in DigitalOcean. "Efficiency" is more important to me than "whizz bang features".

**Comment by prologic** [comment]
> Val Linux is interesting. I will check it out. :)

The only interesting part to be honest is the use of [finit](https://github.com/troglobit/finit)

**Comment by prologic** [comment]
Looks like this all worked!

```
WARNING: If you have created or modified any DOS 6.x
partitions, please see the fdisk manual page for additional
information.
Syncing disks.
mkfs.fat 3.0.26 (2014-03-07)
Loop device does not match a floppy size, using default hd params
1+0 records in
1+0 records out
440 bytes (440 B) copied, 0.0386574 s, 11.4 kB/s
docker cp barge-built:/build/buildroot/output/images/rootfs.tar.xz output/
docker cp barge-built:/build/buildroot/output/images/bzImage output/
docker cp barge-built:/build/buildroot/output/images/barge.iso output/
docker cp barge-built:/build/buildroot/output/images/barge.img output/

prologic@Jamess-MacBook
Tue Jun 26 09:00:10
~/tmp/barge-os
 (ci) 0
$ ls
Dockerfile  LICENSE  Makefile  README.md  Vagrantfile  configs  docs  output  overlay  patches  scripts

prologic@Jamess-MacBook
Tue Jun 26 09:01:38
~/tmp/barge-os
 (ci) 0
$ ls -lah output/
total 41M
drwxr-xr-x  6 prologic _lpoperator  192 Jun 26 09:00 .
drwxr-xr-x 16 prologic _lpoperator  512 Jun 26 09:00 ..
-rw-r--r--  1 prologic _lpoperator  14M Jun 26 09:00 barge.img
-rw-r--r--  1 prologic _lpoperator  14M Jun 26 09:00 barge.iso
-rw-r--r--  1 prologic _lpoperator 2.7M Jun 26 08:58 bzImage
-rw-r--r--  1 prologic _lpoperator  11M Jun 26 08:59 rootfs.tar.xz

```

Congrats on simplifying the build! I love it! Let's merge this as-is -- we can iterate

**Comment by ailispaw** [comment]
@prologic Thank you so much for your confirmation and encouraging me to make this happen. :)

**Pull request merged**
