### PR TITLE
Permit user environment for ssh (~/.ssh/environment)

### PR DESCRIPTION
**Pull request by ailispaw**
and set LANG and PATH by default.

It's not a perfect solution though.

Cf.) http://www.microhowto.info/howto/persistently_set_the_value_of_an_environment_variable_for_all_users.html#idp24224

### CODE REVIEW

**Comment by ailispaw** [comment]
It's not good and beautiful, because same configuration is in two different places.

LANG: `/etc/locale.conf` and `/etc/profile.d/locale.sh`, and `~/.ssh/environment`
PATH: `/etc/profile.d/optbin.sh` and `~/.ssh/environment`

I prefer `-l` option for ssh and cron, or load `/etc/profile` before/within a script.
It's simple and more manageable.

**Comment by tnir** [comment]
I don't think `-l` option of shell is elegant or easy for users.

**Comment by ailispaw** [comment]
@tnir Thank you for your opinion.

I'm still thinking...
This solution is only for SSH.
We still need something for others (cron, sudo and etc.).

It might be good to leave it (and leave this PR open) for users to be aware of this.
At the same time, I think it is OK to merge this anyway, because most of Barge users who use through Vagrant haven't been aware of this, because Vagrant uses `-l` option by default.

I might merge this PR into the next release.

**Comment by ailispaw** [comment]
MEMO:

- sshd (OpenSSH): the default `PATH` is defined on compiling with configure `--with-default-path`.
- crond (busybox): inherites `PATH` from `/etc/init.d/S90crond` and `/init`.
- su (busybox): inherites `PATH` without `-l` option.  
  With `-l` option and `-c`, `su` uses `bb_PATH_root_path` in `include/libbb.h` and `libbb/messege.c`
- login (busybox): uses `bb_PATH_root_path` in `include/libbb.h` and `libbb/messege.c` without `-p` option, but `PATH` will be replaced within `/etc/profile`.
- sudo: inherites `PATH` without `-i` option.  
  With `-i` option, `sudo` runs a login shell.

Therefore, It seems that a solution would be the followings.

- Add `--with-default-path=/usr/sbin:/sbin:/opt/bin:/usr/bin:/bin` in `buildroot/package/openssh/openssh.mk`.
- Set `export PATH=/usr/sbin:/sbin:/opt/bin:/usr/bin:/bin` in `/etc/init.d/S90crond`.
- Set `export PATH=/usr/sbin:/sbin:/opt/bin:/usr/bin:/bin` in `/etc/profile`.
- Set `bb_PATH_root_path` in `busybox/libbb/messege.c` to `PATH=/usr/sbin:/sbin:/opt/bin:/usr/bin:/bin`.

One more question here;
what should the good order of `PATH` directories be?

- `/bin:/sbin:/usr/bin:/usr/sbin` in `system/skeleton/etc/profile` for buildroot.
- `/sbin:/usr/sbin:/bin:/usr/bin` in `libbb/messege.c` for busybox.
- `/usr/bin:/bin:/usr/sbin:/sbin` in `configure.ac` for OpenSSH.
- `/sbin:/bin:/usr/sbin:/usr/bin` in `include/pathnames.h` for util-linux.

So?
- `/` -> `/usr` or `/usr` -> `/`, or doesn't matter
- `bin` -> `sbin` or `sbin` -> `bin`, or doesn't matter

**Comment by tnir** [comment]
I don't think this is a workaround only for ssh but for cron, sudo etc.

Thanks for keeping this open for a while to listen users' voice. 😄

**Comment by ailispaw** [comment]
MEMO2:

in `/etc/sudoers`;
```
## Uncomment to use a hard-coded PATH instead of the user's to find commands
# Defaults secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
```

in `/etc/login.defs` of ubuntu;
```
ENV_SUPATH	PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ENV_PATH	PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
```

**Comment by ailispaw** [comment]
My final answer for `PATH` would be `/usr/sbin:/sbin:/opt/bin:/usr/bin:/bin`.

**Comment by ailispaw** [comment]
will close via #62

**Comment by ailispaw** [comment]
close via #62 and #61

**Pull request closed without merging**
